// AUTO-GENERATED by scripts/gen-hero-stroke-svg.py — real Syncopate glyph geometry.
export const heroStrokeWholeSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20706 2891" preserveAspectRatio="xMidYMid meet" class="hero-stroke-svg">
<defs>
<clipPath id="c0"><path d="M1550 1374 1901 420 2281 1374H2666L2114 0H1702L1343 924L985 0H573L20 1374H406L778 440L1137 1374Z" transform="translate(-40.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c1"><path d="M1530 0V573H586V0H215V1374H586V874H1530V1374H1901V0Z" transform="translate(4944.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c2"><path d="M1993 686Q1993 509 1928.0 373.5Q1863 238 1742.0 147.0Q1621 56 1448.5 9.5Q1276 -37 1061 -37Q846 -37 672.5 9.5Q499 56 377.0 147.0Q255 238 189.0 373.5Q123 509 123 686Q123 863 189.0 998.5Q255 1134 377.0 1225.0Q499 1316 672.5 1362.5Q846 1409 1061 1409Q1276 1409 1448.5 1362.5Q1621 1316 1742.0 1225.0Q1863 1134 1928.0 998.5Q1993 863 1993 686ZM1618 686Q1618 763 1593.5 839.5Q1569 916 1506.5 977.0Q1444 1038 1336.0 1076.0Q1228 1114 1061 1114Q949 1114 864.0 1096.5Q779 1079 717.0 1048.0Q655 1017 613.0 975.5Q571 934 546.0 886.5Q521 839 510.5 787.5Q500 736 500 686Q500 635 510.5 583.0Q521 531 546.0 483.5Q571 436 613.0 395.0Q655 354 717.0 323.5Q779 293 864.0 275.5Q949 258 1061 258Q1228 258 1336.0 296.0Q1444 334 1506.5 395.0Q1569 456 1593.5 532.5Q1618 609 1618 686Z" transform="translate(9360.0 2818.0) scale(2 -2)"/></clipPath>
<clipPath id="c3"><path d="M215 0V1374H586V301H1589V0Z" transform="translate(13408.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c4"><path d="M215 0V1374H1606V1081H596V854H1554V561H596V293H1620V0Z" transform="translate(16750.0 2748.0) scale(2 -2)"/></clipPath>
</defs>
<g fill="#68E3BE">
<path d="M1550 1374 1901 420 2281 1374H2666L2114 0H1702L1343 924L985 0H573L20 1374H406L778 440L1137 1374Z" transform="translate(-40.0 2748.0) scale(2 -2)"/>
<path d="M1530 0V573H586V0H215V1374H586V874H1530V1374H1901V0Z" transform="translate(4944.0 2748.0) scale(2 -2)"/>
<path d="M1993 686Q1993 509 1928.0 373.5Q1863 238 1742.0 147.0Q1621 56 1448.5 9.5Q1276 -37 1061 -37Q846 -37 672.5 9.5Q499 56 377.0 147.0Q255 238 189.0 373.5Q123 509 123 686Q123 863 189.0 998.5Q255 1134 377.0 1225.0Q499 1316 672.5 1362.5Q846 1409 1061 1409Q1276 1409 1448.5 1362.5Q1621 1316 1742.0 1225.0Q1863 1134 1928.0 998.5Q1993 863 1993 686ZM1618 686Q1618 763 1593.5 839.5Q1569 916 1506.5 977.0Q1444 1038 1336.0 1076.0Q1228 1114 1061 1114Q949 1114 864.0 1096.5Q779 1079 717.0 1048.0Q655 1017 613.0 975.5Q571 934 546.0 886.5Q521 839 510.5 787.5Q500 736 500 686Q500 635 510.5 583.0Q521 531 546.0 483.5Q571 436 613.0 395.0Q655 354 717.0 323.5Q779 293 864.0 275.5Q949 258 1061 258Q1228 258 1336.0 296.0Q1444 334 1506.5 395.0Q1569 456 1593.5 532.5Q1618 609 1618 686Z" transform="translate(9360.0 2818.0) scale(2 -2)"/>
<path d="M215 0V1374H586V301H1589V0Z" transform="translate(13408.0 2748.0) scale(2 -2)"/>
<path d="M215 0V1374H1606V1081H596V854H1554V561H596V293H1620V0Z" transform="translate(16750.0 2748.0) scale(2 -2)"/>
</g>
<path id="p0_1" d="M 4032.0 2179.0 L 4036.0 2175.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="582.9" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c0)">
<textPath href="#p0_1" startOffset="50%" text-anchor="middle" textLength="5.4" lengthAdjust="spacingAndGlyphs">Lobby</textPath>
</text>
<path id="p1_12" d="M 5745.0 1300.0 L 8373.0 1300.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="493.6" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c1)">
<textPath href="#p1_12" startOffset="50%" text-anchor="middle" textLength="2522.9" lengthAdjust="spacingAndGlyphs">Pool</textPath>
</text>
<path id="p2_0" d="M 10001.0 1447.0 L 10020.0 1292.0 L 10047.0 1135.0 L 10074.0 1029.0 L 10103.0 949.0 L 10148.0 857.0 L 10206.0 768.0 L 10278.0 683.0 L 10372.0 597.0 L 10477.0 524.0 L 10578.0 469.0 L 10708.0 415.0 L 10827.0 378.0 L 10957.0 348.0 L 11092.0 327.0 L 11249.0 312.0 L 11461.0 300.0 L 11604.0 305.0 L 11818.0 321.0 L 11955.0 339.0 L 12118.0 373.0 L 12234.0 408.0 L 12353.0 456.0 L 12472.0 518.0 L 12573.0 586.0 L 12640.0 643.0 L 12738.0 750.0 L 12796.0 836.0 L 12838.0 919.0 L 12872.0 1005.0 L 12900.0 1103.0 L 12928.0 1260.0 L 12951.0 1439.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="532.5" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c2)">
<textPath href="#p2_0" startOffset="50%" text-anchor="middle" textLength="4068.2" lengthAdjust="spacingAndGlyphs">Theater</textPath>
</text>
<path id="p3_0" d="M 16285.0 2446.0 L 14278.0 2446.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="551.9" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c3)">
<textPath href="#p3_0" startOffset="50%" text-anchor="middle" textLength="1926.7" lengthAdjust="spacingAndGlyphs">Ballroom</textPath>
</text>
<path id="p4_2" d="M 17648.0 2454.0 L 19697.0 2454.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="480.5" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c4)">
<textPath href="#p4_2" startOffset="50%" text-anchor="middle" textLength="1967.0" lengthAdjust="spacingAndGlyphs">Sportsbook</textPath>
</text>
</svg>`;
export const heroStrokePropSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 29496 2891" preserveAspectRatio="xMidYMid meet" class="hero-stroke-svg">
<defs>
<clipPath id="c0"><path d="M1759 905Q1759 802 1729.0 715.5Q1699 629 1632.5 566.5Q1566 504 1460.0 469.0Q1354 434 1202 434H586V0H215V1374H1202Q1354 1374 1460.0 1339.5Q1566 1305 1632.5 1242.5Q1699 1180 1729.0 1094.0Q1759 1008 1759 905ZM1384 899Q1384 947 1370.5 981.5Q1357 1016 1326.0 1038.0Q1295 1060 1245.0 1070.5Q1195 1081 1122 1081H586V727H1122Q1195 727 1245.0 735.5Q1295 744 1326.0 764.5Q1357 785 1370.5 818.0Q1384 851 1384 899Z" transform="translate(-430.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c1"><path d="M586 0H215V1374H1145Q1295 1374 1399.5 1343.0Q1504 1312 1569.5 1255.0Q1635 1198 1664.5 1117.5Q1694 1037 1694 938Q1694 851 1669.5 786.0Q1645 721 1603.5 674.5Q1562 628 1507.0 596.0Q1452 564 1391 543L1841 0H1407L991 506H586ZM1319 940Q1319 980 1308.5 1008.0Q1298 1036 1272.0 1053.5Q1246 1071 1202.5 1079.0Q1159 1087 1094 1087H586V793H1094Q1159 793 1202.5 801.0Q1246 809 1272.0 826.5Q1298 844 1308.5 872.0Q1319 900 1319 940Z" transform="translate(3272.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c2"><path d="M1993 686Q1993 509 1928.0 373.5Q1863 238 1742.0 147.0Q1621 56 1448.5 9.5Q1276 -37 1061 -37Q846 -37 672.5 9.5Q499 56 377.0 147.0Q255 238 189.0 373.5Q123 509 123 686Q123 863 189.0 998.5Q255 1134 377.0 1225.0Q499 1316 672.5 1362.5Q846 1409 1061 1409Q1276 1409 1448.5 1362.5Q1621 1316 1742.0 1225.0Q1863 1134 1928.0 998.5Q1993 863 1993 686ZM1618 686Q1618 763 1593.5 839.5Q1569 916 1506.5 977.0Q1444 1038 1336.0 1076.0Q1228 1114 1061 1114Q949 1114 864.0 1096.5Q779 1079 717.0 1048.0Q655 1017 613.0 975.5Q571 934 546.0 886.5Q521 839 510.5 787.5Q500 736 500 686Q500 635 510.5 583.0Q521 531 546.0 483.5Q571 436 613.0 395.0Q655 354 717.0 323.5Q779 293 864.0 275.5Q949 258 1061 258Q1228 258 1336.0 296.0Q1444 334 1506.5 395.0Q1569 456 1593.5 532.5Q1618 609 1618 686Z" transform="translate(7240.0 2818.0) scale(2 -2)"/></clipPath>
<clipPath id="c3"><path d="M1759 905Q1759 802 1729.0 715.5Q1699 629 1632.5 566.5Q1566 504 1460.0 469.0Q1354 434 1202 434H586V0H215V1374H1202Q1354 1374 1460.0 1339.5Q1566 1305 1632.5 1242.5Q1699 1180 1729.0 1094.0Q1759 1008 1759 905ZM1384 899Q1384 947 1370.5 981.5Q1357 1016 1326.0 1038.0Q1295 1060 1245.0 1070.5Q1195 1081 1122 1081H586V727H1122Q1195 727 1245.0 735.5Q1295 744 1326.0 764.5Q1357 785 1370.5 818.0Q1384 851 1384 899Z" transform="translate(11288.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c4"><path d="M215 0V1374H1606V1081H596V854H1554V561H596V293H1620V0Z" transform="translate(14990.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c5"><path d="M586 0H215V1374H1145Q1295 1374 1399.5 1343.0Q1504 1312 1569.5 1255.0Q1635 1198 1664.5 1117.5Q1694 1037 1694 938Q1694 851 1669.5 786.0Q1645 721 1603.5 674.5Q1562 628 1507.0 596.0Q1452 564 1391 543L1841 0H1407L991 506H586ZM1319 940Q1319 980 1308.5 1008.0Q1298 1036 1272.0 1053.5Q1246 1071 1202.5 1079.0Q1159 1087 1094 1087H586V793H1094Q1159 793 1202.5 801.0Q1246 809 1272.0 826.5Q1298 844 1308.5 872.0Q1319 900 1319 940Z" transform="translate(18516.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c6"><path d="M985 1075V0H614V1075H31V1374H1569V1075Z" transform="translate(22668.0 2748.0) scale(2 -2)"/></clipPath>
<clipPath id="c7"><path d="M1077 561V0H707V561L41 1374H457L893 821L1327 1374H1743Z" transform="translate(25846.0 2748.0) scale(2 -2)"/></clipPath>
</defs>
<g fill="#68E3BE">
<path d="M1759 905Q1759 802 1729.0 715.5Q1699 629 1632.5 566.5Q1566 504 1460.0 469.0Q1354 434 1202 434H586V0H215V1374H1202Q1354 1374 1460.0 1339.5Q1566 1305 1632.5 1242.5Q1699 1180 1729.0 1094.0Q1759 1008 1759 905ZM1384 899Q1384 947 1370.5 981.5Q1357 1016 1326.0 1038.0Q1295 1060 1245.0 1070.5Q1195 1081 1122 1081H586V727H1122Q1195 727 1245.0 735.5Q1295 744 1326.0 764.5Q1357 785 1370.5 818.0Q1384 851 1384 899Z" transform="translate(-430.0 2748.0) scale(2 -2)"/>
<path d="M586 0H215V1374H1145Q1295 1374 1399.5 1343.0Q1504 1312 1569.5 1255.0Q1635 1198 1664.5 1117.5Q1694 1037 1694 938Q1694 851 1669.5 786.0Q1645 721 1603.5 674.5Q1562 628 1507.0 596.0Q1452 564 1391 543L1841 0H1407L991 506H586ZM1319 940Q1319 980 1308.5 1008.0Q1298 1036 1272.0 1053.5Q1246 1071 1202.5 1079.0Q1159 1087 1094 1087H586V793H1094Q1159 793 1202.5 801.0Q1246 809 1272.0 826.5Q1298 844 1308.5 872.0Q1319 900 1319 940Z" transform="translate(3272.0 2748.0) scale(2 -2)"/>
<path d="M1993 686Q1993 509 1928.0 373.5Q1863 238 1742.0 147.0Q1621 56 1448.5 9.5Q1276 -37 1061 -37Q846 -37 672.5 9.5Q499 56 377.0 147.0Q255 238 189.0 373.5Q123 509 123 686Q123 863 189.0 998.5Q255 1134 377.0 1225.0Q499 1316 672.5 1362.5Q846 1409 1061 1409Q1276 1409 1448.5 1362.5Q1621 1316 1742.0 1225.0Q1863 1134 1928.0 998.5Q1993 863 1993 686ZM1618 686Q1618 763 1593.5 839.5Q1569 916 1506.5 977.0Q1444 1038 1336.0 1076.0Q1228 1114 1061 1114Q949 1114 864.0 1096.5Q779 1079 717.0 1048.0Q655 1017 613.0 975.5Q571 934 546.0 886.5Q521 839 510.5 787.5Q500 736 500 686Q500 635 510.5 583.0Q521 531 546.0 483.5Q571 436 613.0 395.0Q655 354 717.0 323.5Q779 293 864.0 275.5Q949 258 1061 258Q1228 258 1336.0 296.0Q1444 334 1506.5 395.0Q1569 456 1593.5 532.5Q1618 609 1618 686Z" transform="translate(7240.0 2818.0) scale(2 -2)"/>
<path d="M1759 905Q1759 802 1729.0 715.5Q1699 629 1632.5 566.5Q1566 504 1460.0 469.0Q1354 434 1202 434H586V0H215V1374H1202Q1354 1374 1460.0 1339.5Q1566 1305 1632.5 1242.5Q1699 1180 1729.0 1094.0Q1759 1008 1759 905ZM1384 899Q1384 947 1370.5 981.5Q1357 1016 1326.0 1038.0Q1295 1060 1245.0 1070.5Q1195 1081 1122 1081H586V727H1122Q1195 727 1245.0 735.5Q1295 744 1326.0 764.5Q1357 785 1370.5 818.0Q1384 851 1384 899Z" transform="translate(11288.0 2748.0) scale(2 -2)"/>
<path d="M215 0V1374H1606V1081H596V854H1554V561H596V293H1620V0Z" transform="translate(14990.0 2748.0) scale(2 -2)"/>
<path d="M586 0H215V1374H1145Q1295 1374 1399.5 1343.0Q1504 1312 1569.5 1255.0Q1635 1198 1664.5 1117.5Q1694 1037 1694 938Q1694 851 1669.5 786.0Q1645 721 1603.5 674.5Q1562 628 1507.0 596.0Q1452 564 1391 543L1841 0H1407L991 506H586ZM1319 940Q1319 980 1308.5 1008.0Q1298 1036 1272.0 1053.5Q1246 1071 1202.5 1079.0Q1159 1087 1094 1087H586V793H1094Q1159 793 1202.5 801.0Q1246 809 1272.0 826.5Q1298 844 1308.5 872.0Q1319 900 1319 940Z" transform="translate(18516.0 2748.0) scale(2 -2)"/>
<path d="M985 1075V0H614V1075H31V1374H1569V1075Z" transform="translate(22668.0 2748.0) scale(2 -2)"/>
<path d="M1077 561V0H707V561L41 1374H457L893 821L1327 1374H1743Z" transform="translate(25846.0 2748.0) scale(2 -2)"/>
</g>
<path id="p0_5" d="M 370.0 371.0 L 449.0 292.0 L 1804.0 293.0 L 2084.0 309.0 L 2167.0 319.0 L 2265.0 338.0 L 2361.0 367.0 L 2448.0 408.0 L 2513.0 455.0 L 2567.0 515.0 L 2596.0 563.0 L 2626.0 639.0 L 2659.0 774.0 L 2687.0 939.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="495.6" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c0)">
<textPath href="#p0_5" startOffset="50%" text-anchor="middle" textLength="2622.8" lengthAdjust="spacingAndGlyphs">Lobby</textPath>
</text>
<path id="p1_7" d="M 4157.0 286.0 L 5349.0 286.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="519.2" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c1)">
<textPath href="#p1_7" startOffset="50%" text-anchor="middle" textLength="1144.3" lengthAdjust="spacingAndGlyphs">Pool</textPath>
</text>
<path id="p2_0" d="M 7881.0 1447.0 L 7900.0 1292.0 L 7927.0 1135.0 L 7954.0 1029.0 L 7983.0 949.0 L 8028.0 857.0 L 8086.0 768.0 L 8158.0 683.0 L 8252.0 597.0 L 8357.0 524.0 L 8458.0 469.0 L 8588.0 415.0 L 8707.0 378.0 L 8837.0 348.0 L 8972.0 327.0 L 9129.0 312.0 L 9341.0 300.0 L 9484.0 305.0 L 9698.0 321.0 L 9835.0 339.0 L 9998.0 373.0 L 10114.0 408.0 L 10233.0 456.0 L 10352.0 518.0 L 10453.0 586.0 L 10520.0 643.0 L 10618.0 750.0 L 10676.0 836.0 L 10718.0 919.0 L 10752.0 1005.0 L 10780.0 1103.0 L 10808.0 1260.0 L 10831.0 1439.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="532.5" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c2)">
<textPath href="#p2_0" startOffset="50%" text-anchor="middle" textLength="4068.2" lengthAdjust="spacingAndGlyphs">Theater</textPath>
</text>
<path id="p3_5" d="M 12088.0 371.0 L 12167.0 292.0 L 13522.0 293.0 L 13802.0 309.0 L 13885.0 319.0 L 13983.0 338.0 L 14079.0 367.0 L 14166.0 408.0 L 14231.0 455.0 L 14285.0 515.0 L 14314.0 563.0 L 14344.0 639.0 L 14377.0 774.0 L 14405.0 939.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="495.6" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c3)">
<textPath href="#p3_5" startOffset="50%" text-anchor="middle" textLength="2622.8" lengthAdjust="spacingAndGlyphs">Ballroom</textPath>
</text>
<path id="p4_2" d="M 15888.0 2454.0 L 17937.0 2454.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="480.5" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c4)">
<textPath href="#p4_2" startOffset="50%" text-anchor="middle" textLength="1967.0" lengthAdjust="spacingAndGlyphs">Sportsbook</textPath>
</text>
<path id="p5_7" d="M 19401.0 286.0 L 20593.0 286.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="519.2" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c5)">
<textPath href="#p5_7" startOffset="50%" text-anchor="middle" textLength="1144.3" lengthAdjust="spacingAndGlyphs">Marquee</textPath>
</text>
<path id="p6_4" d="M 24266.0 371.0 L 24266.0 2376.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="608.4" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c6)">
<textPath href="#p6_4" startOffset="50%" text-anchor="middle" textLength="1924.8" lengthAdjust="spacingAndGlyphs">Restaurant</textPath>
</text>
<path id="p7_3" d="M 27630.0 1473.0 L 27739.0 1364.0" fill="none" stroke="none"/>
<text font-family="Space Grotesk, sans-serif" font-weight="700" font-size="506.5" fill="#0A161C" letter-spacing="-0.01em" clip-path="url(#c7)">
<textPath href="#p7_3" startOffset="50%" text-anchor="middle" textLength="148.0" lengthAdjust="spacingAndGlyphs">Bar & lounge</textPath>
</text>
</svg>`;
export const heroStrokeZones = ['Lobby', 'Pool', 'Theater', 'Ballroom', 'Sportsbook', 'Marquee', 'Restaurant', 'Bar & lounge', 'Casino floor', 'Event Venue', 'Conference Room', 'Parking structure', 'Wayfinding sign'];
